### PR TITLE
Add Host GPIO function for Ibiza

### PR DESCRIPTION
**Pull request by Henryshi2032**
change the GPIO mapping according to Ibiza board design and GPIO structure size.

### CODE REVIEW

**Review by wwang22 — COMMENTED** [review]
mecc172x_cfg_host[]  defined in adl_n_mec172x.c has 8 elements,  extern mecc172x_cfg_host[12] is hardcoded to 12 in gpiomgmt.c. These two places are not consistent.

**Review by jjdalynh — APPROVED** [review]
ok

**Comment by jjdalynh** [comment]
you need to expand the .c file in the review.   git only shows a few lines around each change.  there are 12 elements in the struct.

**Review by wwang22 — APPROVED** [review]
oh, my bad.

**Pull request merged**
